variable "bastion_host_private_ip" {}
variable "bastion_host_public_ip" {}
variable "env_prefix" {}
variable "public_key_location" {}
variable "instance_type" {}
variable "avail_zone" {}
variable "subnet_id" {}
variable "private_key_location" {}
variable "aws_vpc" {}
variable "instance_count" {}
variable "alb_security_group" {}